# Generated by Django 2.1.7 on 2019-09-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_genetics', '0002_auto_20190905_0156'),
    ]

    operations = [
        migrations.CreateModel(
            name='gnuhealth_patient_genetic_risk',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease_gene', models.IntegerField()),
                ('health_prof', models.IntegerField()),
                ('natural_varient', models.IntegerField()),
                ('notes', models.CharField(max_length=100)),
                ('onset', models.IntegerField()),
                ('patient', models.IntegerField()),
                ('varient_phenotype', models.IntegerField()),
            ],
        ),
    ]
