# Generated by Django 2.1.7 on 2019-09-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_genetics', '0003_gnuhealth_patient_genetic_risk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gnuhealth_patient_genetic_risk',
            old_name='health_prof',
            new_name='healthprof',
        ),
    ]
