# Generated by Django 2.1.7 on 2019-09-13 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_genetics', '0004_auto_20190913_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnuhealth_patient_genetic_risk',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
