# Generated by Django 2.1.7 on 2019-09-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_genetics', '0005_auto_20190913_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gnuhealth_patient_genetic_risk',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
