# Generated by Django 2.1.7 on 2019-08-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gnuhealth_icu_apache2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('aado2', models.IntegerField()),
                ('age', models.IntegerField()),
                ('apache_score', models.IntegerField()),
                ('arf', models.BooleanField()),
                ('chronic_condition', models.BooleanField()),
                ('create_date', models.DateTimeField(max_length=6)),
                ('create_uid', models.IntegerField()),
                ('fio2', models.IntegerField()),
                ('gcs', models.IntegerField()),
                ('heart_rate', models.IntegerField()),
                ('hematocrit', models.IntegerField()),
                ('hospital_admission_type', models.CharField(max_length=100)),
                ('mean_ap', models.IntegerField()),
                ('name', models.IntegerField()),
                ('paco2', models.IntegerField()),
                ('pao2', models.IntegerField()),
                ('ph', models.IntegerField()),
                ('respiratory_rate', models.IntegerField()),
                ('score_date', models.DateTimeField()),
                ('serum_creatinine', models.IntegerField()),
                ('serum_potassium', models.IntegerField()),
                ('serum_sodium', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('wbc', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gnuhealth_icu_chest_drainage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('air_leak', models.BooleanField()),
                ('create_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('fluid_aspect', models.CharField(max_length=100)),
                ('fluid_volume', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('name', models.IntegerField()),
                ('oscillation', models.BooleanField()),
                ('remarks', models.CharField(max_length=100)),
                ('suction', models.BooleanField()),
                ('suction_pressure', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gnuhealth_icu_glasgow',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('evaluation_date', models.DateTimeField()),
                ('glasgow', models.IntegerField()),
                ('glasgow_eyes', models.CharField(max_length=100)),
                ('glasgow_motor', models.CharField(max_length=100)),
                ('glasgow_verbal', models.CharField(max_length=100)),
                ('name', models.IntegerField()),
                ('write_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gnuhealth_icu_ventilation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField()),
                ('create_uid', models.IntegerField()),
                ('current_mv', models.BooleanField()),
                ('ett_size', models.IntegerField()),
                ('mv_end', models.DateTimeField()),
                ('mv_start', models.DateTimeField()),
                ('name', models.IntegerField()),
                ('remarks', models.CharField(max_length=100)),
                ('tracheostomy_size', models.IntegerField()),
                ('ventilation', models.CharField(max_length=100)),
                ('write_date', models.DateTimeField()),
                ('write_uid', models.IntegerField()),
            ],
        ),
    ]
