# Generated by Django 2.1.7 on 2019-08-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='health_condition',
        ),
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='procedure',
        ),
    ]
