# Generated by Django 2.1.7 on 2019-08-29 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20190830_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnuhealth_pol',
            name='health_condition',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='health.gnuhealth_pathology'),
        ),
        migrations.AddField(
            model_name='gnuhealth_pol',
            name='institution',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='health.gnuhealth_institution'),
        ),
        migrations.AddField(
            model_name='gnuhealth_pol',
            name='procedure',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='health.gnuhealth_procedure'),
        ),
    ]
