# Generated by Django 2.1.7 on 2019-08-29 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_auto_20190830_0049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='health_condition',
        ),
    ]
