# Generated by Django 2.1.7 on 2019-08-29 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_remove_gnuhealth_pol_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='gnuhealth_pol',
            name='health_condition',
            field=models.ForeignKey(default='SOME STRING', on_delete=django.db.models.deletion.CASCADE, to='health.gnuhealth_pathology'),
        ),
    ]
