# Generated by Django 2.1.7 on 2019-08-29 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_gnuhealth_pol_health_condition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('page', models.CharField(max_length=100)),
                ('node', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='health_condition',
        ),
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='gnuhealth_pol',
            name='procedure',
        ),
    ]
