# Generated by Django 2.1.7 on 2019-08-29 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20190830_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gnuhealth_institution',
            name='name',
        ),
        migrations.DeleteModel(
            name='gnuhealth_pathology',
        ),
        migrations.DeleteModel(
            name='gnuhealth_pol',
        ),
        migrations.DeleteModel(
            name='gnuhealth_procedure',
        ),
        migrations.DeleteModel(
            name='gnuhealth_institution',
        ),
        migrations.DeleteModel(
            name='party_party',
        ),
    ]
