from django.db import models

# Create your models here.

class gnuhealth_inpatient_meal(models.Model):
  id = models.IntegerField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  diet_belief = models.CharField()
  diet_therapeutic = models.CharField()
  diet_vegetarian = models.CharField()
  institution = models.CharField()
  name = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
class gnuhealth_inpatient_meal_order_item(models.Model):
  id = models.IntegerField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  meal = models.CharField()
  name = models.CharField()
  remarks = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
class gnuhealth_inpatient_medication(models.Model):
  id = models.IntegerField()
  adverse_reaction = models.CharField()
  common_dosage = models.CharField()
  course_completed = models.CharField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  discontinued = models.BooleanField()
  discontinued_reason = models.CharField()
  dose = models.IntegerField()
  dose_unit = models.CharField()
  end_treatment = models.CharField()
  form = models.CharField()
  frequency = models.IntegerField()
  frquency_prn = models.CharField()
  frequency_unit = models.CharField()
  indication = models.CharField()
  is_active = models.BooleanField()
  medicament = models.CharField()
  name = models.CharField()
  qty = models.IntegerField()
  route = models.CharField()
  start_treatment = models.CharField()
  
class gnuhealth_inpatient_medication_admin_time(models.Model):  
  id = models.IntegerField()
  admin_time = models.TimeField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  dose = models.IntegerField()
  dose_unit = models.CharField()
  name = models.CharField()
  remarks = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
class gnuhealth_inpatient_registration(models.Model):
  id = models.IntegerField()
  admission_reason = models.CharField()
  admission_type = models.CharField()
  attending_physician = models.CharField()
  bed = models.CharField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  discharge_date = models.DateField()
  discharge_dx = models.CharField()
  discharge_plan = models.CharField()
  discharge_reason = models.CharField()
  discharge_by = models.CharField()
  hospitalization_date = models.DateField()
  info = models.CharField()
  institution = models.CharField()
  name = models.CharField()
  nursing_plan = models.CharField()
  nutrition_notes = models.CharField()
  operating_physician = models.CharField()
  patient = models.CharField()
  state = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  event = models.CharField()
  icu = models.CharField()
  
class gnuhealth_inpatient_medication_log(models.Model):
  id = models.IntegerField()
  admin_time = models.TimeField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  dose = models.IntegerField()
  dose_unit = models.CharField()
  health_professional = models.CharField()
  name = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
class gnuhealth_inpatient_meal_order(models.Model):
  id = models.IntegerField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  health_professional = models.CharField()
  meal_order = models.CharField()
  meal_warning = models.CharField()
  meal_warning_ack = models.CharField()
  mealtime = models.TimeField()
  name = models.CharField()
  order_date = models.DateField()
  remarks = models.CharField()
  state = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
class gnuhealth_inpatient_icu(models.Model):
  id = models.IntegerField()
  admitted = models.BooleanField()
  create_date = models.DateField()
  create_uid = models.IntegerField()
  discharged_from_icu = models.BooleanField()
  icu_admission_date = models.DateField()
  icu_discharge_date = models.DateField()
  name = models.CharField()
  write_date = models.DateField()
  write_uid = models.IntegerField()
  
  
  
  
